version: '3'
services:

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - zhibo-network
    volumes:
      - maven_m2:/root/.m2
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    restart: always
    networks:
      - zhibo-network

  nest:
    build:
      context: ../zhibo_spider/
    networks:
      - zhibo-network
    restart: always
    depends_on:
      - redis
    ports:
    - "3000:3000"

#在最顶层定义时会自动创建这个网络
networks:
  zhibo-network:

volumes:
  maven_m2: