spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zhibo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123

  redis:
    host: localhost # Redis服务器地址

my:
  nest:
    host: localhost