spring:
  datasource:
    url: jdbc:mysql://db:3306/zhibo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

  redis:
      host: redis # Redis服务器地址